### ISSUE TITLE
Page wont update even after refresh

### ISSUE THREAD

**Issue by Aceship** [MurakumoIndustries/Gear#3]
Some new gear doesn't appear even after normal refresh, need to do force refresh (ctrl+shift+R on firefox), might be caching issue ?

also happening on some other page like the actress page, where the tab of costume and accesories doesnt appear until i do that force refresh

**Comment by WindWT** [comment]
It's intended. All murakumo sites are [PWAs](https://developers.google.com/web/progressive-web-apps/) now, which means when there is an update, it will fetch in background instead of directly download from server, and use cache to (dramaticly) shorten load time.
I'll add a switch `Disable Cache` (somewhere near "External Sites") to disable this feature. Still, it's not recommended for most users.

(you may need another force refresh to see this switch :)

**Comment by Aceship** [comment]
is it possible to add a force refresh cache automatically only when there is new update ?

**Comment by WindWT** [comment]
`Disable Cache` actually only disables PWA, while data files are still cached and update automatically only when new data files are uploaded.
